title: L'Hessistant
email: contact@ju4.fr
description: >-
  Trouve un job au service de la communaut√© !
baseurl: "/Hessistant" # the subpath of your site, e.g. /blog
url: "https://ju4.fr" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  jobs:
    output: true

defaults:
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
